name: Andy Bradbury
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7109191920608282
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0e0e0'
    - '#333333'
    - '#c5112f'
    - '#080302'
    - '#b7b7b7'
  brandStrength: 0.8125
  lightness: 0.12949336669407785
  saturation: 0.9610111720394343
  rhythmicContrast: 0.47293009515851736
purpose: []
