name: Andy Bradbury
favicon: null
layout_spectrum: 0.85424
typography_spectrum: 0.7109191920608282
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3769cc'
    - '#68c599'
    - '#ffffff'
    - '#363844'
    - '#81828a'
  brandStrength: 0.75
  lightness: 0.12949336669407785
  saturation: 0.9610111720394343
  rhythmicContrast: 0.47293009515851736
purpose: []
