name: Andy Bradbury
favicon: null
layout_spectrum: 0.8189634175505489
typography_spectrum: 0.7109191920608282
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5042951940558851
  lightness: 0.12949336669407785
  saturation: 0.9610111720394343
  rhythmicContrast: 0.47293009515851736
purpose: []
